#  Market Basket Analysis using Apriori Algorithm

###  Objective:
To find frequent itemsets and association rules from transaction data.

###  Algorithm Used:
- Apriori Algorithm

###  Dataset:
Groceries Dataset (Kaggle)

In [1]:
# Install required libraries 
!pip install pandas mlxtend

Requirement already satisfied: pandas in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.16.3 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (1.16.3)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: joblib>=1.5.2 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\tirupati\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ---------------------------------------- 1.4/1.4 MB 8.4 MB/s  0:00:00
Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.3 MB 11.6 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.3 MB 11.6 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.3 MB 11.6 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.3 MB 11.6 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 11.0 MB/s  0:00:01
Using cached scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
Installing collected packages: numpy, scikit-learn, matplotlib, mlxtend

  Attempting uninstall: numpy

    Found existing installation: numpy 2.2.6

   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
    Uninstalling numpy-2.2.6:
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
      Successfully uninstalled numpy-2.2.6
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
   ---------------------------------------- 0/4 [numpy]
  Attempting uninstall: scikit-learn
   ---------------------------------------- 0/4 [numpy]
    Found existing installation: scikit-learn 1.7.2
   ---------------------------------------- 0/4 [numpy]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
    Uninstalling scikit-learn-1.7.2:
   ---------- ----------------------------- 1/4 [scikit-learn]
      Successfully uninstalled scikit-learn-1.7.2
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
   ---------- ----------------------------- 1/4 [scikit-learn]
  Attempting uninstall: matplotlib
   ---------- ----------------------------- 1/4 [scikit-learn]
    Found existing installation: matplotlib 3.10.7
   ---------- ----------------------------- 1/4 [scikit-learn]
   -------------------- ------------------- 2/4 [matplotlib]
    Uninstalling matplotlib-3.10.7:
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
      Successfully uninstalled matplotlib-3.10.7
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   -------------------- ------------------- 2/4 [matplotlib]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]
   ------------------------------ --------- 3/4 [mlxtend]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\Tirupati\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

##  Step 1: Import Libraries

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

##  Step 2: Load Dataset

In [9]:
import zipfile
zip_path = "dataset.zip"

# Open the zip file
with zipfile.ZipFile(zip_path, 'r') as z:
    # List files inside zip
    print(z.namelist())
    
    # Replace 'your_file.csv' with actual file name inside zip
    with z.open('Groceries_dataset.csv') as f:
        df = pd.read_csv(f)

# Print first 5 rows
print(df.head())

['Groceries_dataset.csv']
   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

##  Step 3: Data Preprocessing

Convert data into transaction format

In [11]:
# Convert dataset into transactions
transactions = df.groupby('Member_number')['itemDescription'].apply(list)

# Convert to list format
transactions = transactions.tolist()

# Show sample transactions
transactions[:5]

[['soda',
  'canned beer',
  'sausage',
  'sausage',
  'whole milk',
  'whole milk',
  'pickled vegetables',
  'misc. beverages',
  'semi-finished bread',
  'hygiene articles',
  'yogurt',
  'pastry',
  'salty snack'],
 ['frankfurter',
  'frankfurter',
  'beef',
  'sausage',
  'whole milk',
  'soda',
  'curd',
  'white bread',
  'whole milk',
  'soda',
  'whipped/sour cream',
  'rolls/buns'],
 ['tropical fruit',
  'butter milk',
  'butter',
  'frozen vegetables',
  'sugar',
  'specialty chocolate',
  'whole milk',
  'other vegetables'],
 ['sausage',
  'root vegetables',
  'rolls/buns',
  'detergent',
  'frozen meals',
  'rolls/buns',
  'dental care',
  'rolls/buns'],
 ['other vegetables',
  'pip fruit',
  'root vegetables',
  'canned beer',
  'rolls/buns',
  'whole milk',
  'other vegetables',
  'hygiene articles',
  'whole milk',
  'whole milk',
  'frozen fish',
  'red/blush wine',
  'chocolate',
  'shopping bags',
  'dish cleaner',
  'packaged fruit/vegetables',
  'tropical fruit',
  'rolls/buns',
  'cling film/bags',
  'chocolate',
  'pastry']]

## Step 4: One-Hot Encoding

Convert transactions into binary matrix

In [12]:
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

df = pd.DataFrame(te_array, columns=te.columns_)

df.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,True,False,True,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

##  Step 5: Apply Apriori Algorithm

Generate frequent itemsets

In [13]:
frequent_itemsets = apriori(df, min_support=0.02, use_colnames=True)

# Show top itemsets
frequent_itemsets.sort_values(by="support", ascending=False).head(10)

      support                        itemsets
85   0.458184                    (whole milk)
52   0.376603              (other vegetables)
64   0.349666                    (rolls/buns)
73   0.313494                          (soda)
86   0.282966                        (yogurt)
79   0.233710                (tropical fruit)
65   0.230631               (root vegetables)
6    0.213699                 (bottled water)
68   0.206003                       (sausage)
485  0.191380  (other vegetables, whole milk)

## Step 6: Generate Association Rules

In [14]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

# Sort by lift
rules = rules.sort_values(by="lift", ascending=False)

rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

,antecedents,consequents,support,confidence,lift
242,"(soda, sausage, whole milk)",(rolls/buns),0.021036,0.525641,1.503264
220,"(yogurt, bottled water, other vegetables)",(whole milk),0.022063,0.682540,1.489664
225,"(other vegetables, sausage, whole milk)",(rolls/buns),0.026167,0.520408,1.488299
153,"(root vegetables, newspapers)",(rolls/buns),0.020010,0.516556,1.477283
217,"(soda, bottled water, whole milk)",(other vegetables),0.022063,0.551282,1.463827
8,(cat food),(other vegetables),0.024115,0.549708,1.459646
219,"(yogurt, bottled water, whole milk)",(other vegetables),0.022063,0.547771,1.454503
244,"(yogurt, sausage, whole milk)",(rolls/buns),0.022832,0.508571,1.454447
46,"(UHT-milk, whole milk)",(other vegetables),0.022063,0.544304,1.445297
60,"(shopping bags, bottled beer)",(whole milk),0.020010,0.661017,1.442690

##  Step 7: Filter Strong Rules

High confidence and high lift rules

In [15]:
strong_rules = rules[
    (rules['confidence'] >= 0.6) &
    (rules['lift'] > 1)
]

strong_rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

,antecedents,consequents,support,confidence,lift
220,"(yogurt, bottled water, other vegetables)",(whole milk),0.022063,0.682540,1.489664
60,"(shopping bags, bottled beer)",(whole milk),0.020010,0.661017,1.442690
232,"(yogurt, rolls/buns, other vegetables)",(whole milk),0.034377,0.656863,1.433623
98,"(shopping bags, canned beer)",(whole milk),0.022063,0.656489,1.432806
238,"(yogurt, soda, other vegetables)",(whole milk),0.027963,0.648810,1.416047
240,"(yogurt, tropical fruit, other vegetables)",(whole milk),0.021293,0.648438,1.415235
222,"(pastry, rolls/buns, other vegetables)",(whole milk),0.020780,0.642857,1.403056
228,"(shopping bags, rolls/buns, other vegetables)",(whole milk),0.021036,0.640625,1.398184
243,"(yogurt, sausage, rolls/buns)",(whole milk),0.022832,0.640288,1.397448
125,"(yogurt, curd)",(whole milk),0.025398,0.630573,1.376246
216,"(bottled water, rolls/buns, other vegetables)",(whole milk),0.023089,0.629371,1.373621
226,"(sausage, rolls/buns, other vegetables)",(whole milk),0.026167,0.625767,1.365755
105,"(yogurt, chocolate)",(whole milk),0.020010,0.624000,1.361899
236,"(yogurt, sausage, other vegetables)",(whole milk),0.023089,0.620690,1.354674
103,"(chocolate, other vegetables)",(whole milk),0.023858,0.620000,1.353169
197,"(root vegetables, shopping bags)",(whole milk),0.029246,0.616216,1.344911
146,"(hamburger meat, other vegetables)",(whole milk),0.021806,0.615942,1.344312
87,"(yogurt, brown bread)",(whole milk),0.025911,0.615854,1.344120
64,"(brown bread, bottled water)",(whole milk),0.023345,0.614865,1.341962
52,"(yogurt, beef)",(whole milk),0.023602,0.613333,1.338619
123,"(curd, soda)",(whole milk),0.026424,0.613095,1.338099
138,"(frozen vegetables, rolls/buns)",(whole milk),0.024885,0.606250,1.323159
81,"(yogurt, bottled water)",(whole milk),0.040277,0.606178,1.323001
57,"(bottled beer, rolls/buns)",(whole milk),0.038225,0.605691,1.321939
229,"(soda, rolls/buns, other vegetables)",(whole milk),0.031811,0.604878,1.320165
50,"(root vegetables, beef)",(whole milk),0.020010,0.604651,1.319670
67,"(curd, bottled water)",(whole milk),0.020010,0.604651,1.319670
56,"(bottled beer, pastry)",(whole milk),0.020267,0.603053,1.316183
209,"(shopping bags, yogurt)",(whole milk),0.033094,0.602804,1.315638
104,"(chocolate, rolls/buns)",(whole milk),0.022576,0.602740,1.315498
179,"(yogurt, pastry)",(whole milk),0.034890,0.601770,1.313381
218,"(soda, bottled water, other vegetables)",(whole milk),0.022063,0.601399,1.312571
49,"(beef, rolls/buns)",(whole milk),0.024371,0.601266,1.312281
48,"(beef, other vegetables)",(whole milk),0.030528,0.601010,1.311723
190,"(shopping bags, rolls/buns)",(whole milk),0.041303,0.600746,1.311147
173,"(pastry, pip fruit)",(whole milk),0.024628,0.600000,1.309518
92,"(yogurt, butter)",(whole milk),0.026937,0.600000,1.309518

##  Step 8: Save Results

In [16]:
frequent_itemsets.to_csv("frequent_itemsets.csv", index=False)
rules.to_csv("association_rules.csv", index=False)

print(" Results saved successfully!")

 Results saved successfully!

In [24]:
def recommend_products_smart(rules, user_items):
    recommendations = {}
    
    user_items = [item.strip().lower() for item in user_items]

    for _, row in rules.iterrows():
        antecedent = [item.strip().lower() for item in row['antecedents']]
        consequent = list(row['consequents'])
        confidence = row['confidence']

        # ✅ Agar user item antecedent me hai (partial match)
        if any(item in antecedent for item in user_items):
            for item in consequent:
                if item not in user_items:
                    if item not in recommendations:
                        recommendations[item] = confidence
                    else:
                        recommendations[item] += confidence

    # Sort by confidence (best recommendations first)
    sorted_recommendations = sorted(recommendations.items(), key=lambda x: x[1], reverse=True)

    return [item[0] for item in sorted_recommendations]

In [27]:
user_input = ['whole milk']

recommended = recommend_products_smart(rules, user_input)

print("Recommended:", recommended[:10])

Recommended: ['other vegetables', 'rolls/buns']

In [28]:
recommended = recommend_products_smart(rules, ['whole milk'])

print("Top 5 Recommendations:", recommended[:5])

Top 5 Recommendations: ['other vegetables', 'rolls/buns']

In [29]:
def recommend_with_score(rules, user_items):
    results = {}

    user_items = [item.strip().lower() for item in user_items]

    for _, row in rules.iterrows():
        antecedent = [i.strip().lower() for i in row['antecedents']]
        consequent = list(row['consequents'])
        confidence = row['confidence']

        if any(item in antecedent for item in user_items):
            for item in consequent:
                if item not in results:
                    results[item] = confidence
                else:
                    results[item] += confidence

    return sorted(results.items(), key=lambda x: x[1], reverse=True)


print(recommend_with_score(rules, ['whole milk']))

[('other vegetables', 6.776163873495325), ('rolls/buns', 1.5546206174777604)]

In [30]:
# Only strong rules (better results)
strong_rules = rules[(rules['confidence'] > 0.3) & (rules['lift'] > 1)]

# Store combinations
combinations = []

for _, row in strong_rules.iterrows():
    items = list(row['antecedents']) + list(row['consequents'])
    
    if len(items) >= 2:
        combinations.append({
            "items": items,
            "confidence": row['confidence'],
            "lift": row['lift']
        })

# Sort by lift (strong relation first)
combinations = sorted(combinations, key=lambda x: x['lift'], reverse=True)

# Show top combinations
for combo in combinations[:10]:
    print(combo)

{'items': ['soda', 'sausage', 'whole milk', 'rolls/buns'], 'confidence': 0.5256410256410255, 'lift': 1.5032639163233439}
{'items': ['yogurt', 'bottled water', 'other vegetables', 'whole milk'], 'confidence': 0.6825396825396826, 'lift': 1.489663876002062}
{'items': ['other vegetables', 'sausage', 'whole milk', 'rolls/buns'], 'confidence': 0.5204081632653061, 'lift': 1.488298620989115}
{'items': ['root vegetables', 'newspapers', 'rolls/buns'], 'confidence': 0.5165562913907285, 'lift': 1.4772827761122962}
{'items': ['soda', 'bottled water', 'whole milk', 'other vegetables'], 'confidence': 0.5512820512820512, 'lift': 1.4638265912107873}
{'items': ['cat food', 'other vegetables'], 'confidence': 0.5497076023391813, 'lift': 1.4596459359115317}
{'items': ['yogurt', 'bottled water', 'whole milk', 'other vegetables'], 'confidence': 0.5477707006369427, 'lift': 1.454502854961037}
{'items': ['yogurt', 'sausage', 'whole milk', 'rolls/buns'], 'confidence': 0.5085714285714286, 'lift': 1.4544471229430878}
{'items': ['UHT-milk', 'whole milk', 'other vegetables'], 'confidence': 0.5443037974683544, 'lift': 1.445297140689132}
{'items': ['shopping bags', 'bottled beer', 'whole milk'], 'confidence': 0.6610169491525424, 'lift': 1.4426898475904872}

In [31]:
top3 = combinations[:3]

for combo in top3:
    print("Place Together:", combo['items'])

Place Together: ['soda', 'sausage', 'whole milk', 'rolls/buns']
Place Together: ['yogurt', 'bottled water', 'other vegetables', 'whole milk']
Place Together: ['other vegetables', 'sausage', 'whole milk', 'rolls/buns']